# Generated by Django 4.2.4 on 2023-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bookings_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
